### ISSUE TITLE
sidebar spacing

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#28]
The sidebar spacing is too compact, especially when items happen to wrap across lines.

<img width="257" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/158537b9-b3e0-4d96-9ac1-f0b4fc393cbb">

Compare to the "cosmo" presentation:

<img width="253" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/529fa0c3-6426-4f0a-8814-63ef3dae5b18">

There is not as much of a contrast on the TOC right-hand-side navigation:

<img width="280" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/f9adaa80-44e3-4968-a4da-143bece2dd24">

With "cosmo":

<img width="284" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/469b9a28-1d75-4abe-a37e-87145e00dce3">

The TOC navigation has a sufficient amount of separation between items and does not feel especially compact when entries happen to wrap.

**Comment by aronatkins** [comment]
This was a similar issue that I had filed: https://github.com/quarto-dev/quarto-cli/issues/5640

I'm not sure what is the responsibility of the theme versus Quarto itself.

**Comment by AshleyHenry15** [comment]
>There is not as much of a contrast on the TOC right-hand-side navigation:
Yeah - that is the posit blue color which doesn't quite pop as much (this was a requirement).

I have been messing around with some of this in the dark theme PR that I have to increase the font weight so there is more constrast in the TOC for light theme as well (it wasn't passing accessibility standards in dark mode): https://github.com/posit-dev/product-doc-theme/tree/dark-theme-blue-option

**Comment by AshleyHenry15** [comment]
@aronatkins 
The spacing for the two is identical (including the margins):

<img width="1409" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/31460023/c3914339-4f8d-46a6-9d4e-2f362137861c">

<img width="1475" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/31460023/bcd2de85-5ba5-4d18-8c4b-75bdc4d8ab21">

I _think_ that Cosmo uses Source Sans Pro and we are using Open Sans. So there will be a lot of slight differences based on that alone.

We could increase spacing a bit if you think that will help but they are current set to the same.

Let me know what you think

**Comment by AshleyHenry15** [comment]
If we change the letter spacing to match what the body font is, I think that improves it a bit?

<img width="941" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/31460023/0cb7b131-edb3-4069-8766-2b6bb3963830">
