### ISSUE TITLE
callouts are more muted

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#32]
This difference may be intentional; filing to track that change.

This theme uses a more muted shared of red for important callouts. For example:

<img width="694" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/8b3627c7-7ad4-4654-bd95-80ea5f880602">

This same callout with cosmo:

<img width="673" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/f6be7a77-8129-48bb-8f31-aceb0826ce91">

**Comment by aronatkins** [comment]
The difference is less obvious for Note.

Theme:

<img width="674" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/c3cb4d88-6063-4ab3-b46e-833e9459b33d">

cosmo:

<img width="663" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/92622610-8be0-49b7-b02d-59c01b8e00d9">

**Comment by aronatkins** [comment]
Warning has chosen to use a more yellow color.

Theme:

<img width="668" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/5f78978e-a720-47de-a299-e5600e1f804f">

Cosmo:

<img width="669" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/5994de1e-6833-42da-b468-23d7ae8134df">

**Comment by aronatkins** [comment]
Tip is a darker shade.

Theme:

<img width="676" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/6a7359c8-6cef-447c-8dda-b5f89bf98893">

Cosmo:

<img width="663" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/ee6e7abd-c8bc-451b-9157-e1a3b4c14a0b">

**Comment by AshleyHenry15** [comment]
This is the default (without the cosmo theme). They appear very similar to what quarto.org has which leads me to believe that this is the default for quarto.

**Comment by AshleyHenry15** [comment]
We can keep this open for tracking but unless it doesn't meet accessibility standards, I think that this is something that we leave.

**Comment by aronatkins** [comment]
I'm fine closing. It's not a Quarto default, but the "default" theme.

default: https://bootswatch.com/default/
cosmo: https://bootswatch.com/cosmo/

**Comment by aronatkins** [comment]
Quarto describes its themes and the Bootstrap default: https://quarto.org/docs/output-formats/html-themes.html

**Comment by aronatkins** [comment]
Making trouble. 😈  We could:

```yaml
  formats:
    html:
      theme: [cosmo, theme.scss]
```

**Comment by AshleyHenry15** [comment]
> Making trouble. 😈 We could:
> 
> ```yaml
>   formats:
>     html:
>       theme: [cosmo, theme.scss]
> ```

@aronatkins - isn't this what we were trying to avoid in the first place? 😭

**Comment by aronatkins** [comment]
> isn't this what we were trying to avoid in the first place?

No, not really. This suggestion is modifying what theme is used as the starting point for our theme.

Today, we have:

```yaml
    html:
      theme: [theme.scss]
```

If I understand how Quarto merges themes correctly, this is effectively the same as:

```yaml
    html:
      theme: [default, theme.scss]
```

I might be wrong about `default`, though, and the starting point might be `none`.

I was suggesting that we could choose any of the Bootstrap themes, like `cerulean` or `cosmo`, as the basis for the theme rather than building on the default. If one of the themes is close to what we want, it could decrease some of the styling we need to do ourselves.

That said, `default` is fine, and it explains the callout styling differences for Connect.
