### ISSUE TITLE
remove posit doc icon/link from footer

### ISSUE THREAD

**Issue by wydsith** [posit-dev/product-doc-theme#40]
We currently have a small icon/link back to docs home in the footer of the theme

![image](https://github.com/posit-dev/product-doc-theme/assets/119340097/3ca329d7-500b-46f6-b0c2-354149e9c7ae)

but the icon is not really readable or intuitive at the current sizing, and it's also redundant since we have a link back to docs home from the top nav drop down

![image](https://github.com/posit-dev/product-doc-theme/assets/119340097/b2f27c98-02cd-4f1c-b9d3-920102c92bf0)

I think between being redundant and not intuitive, we should remove the docs icon from the footer entirely and just keep the top nav link

**Comment by AshleyHenry15** [comment]
I think that all of the icons will require at least some exploration on the user's part. Each displays the URL that they are linked to so I think that I am a bit less worried about each being super intuitive. 

<img width="882" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/31460023/72ab247b-003f-4246-ab7d-59d264b1b4fa">


That being said, this was designed by marketing as our "docs" icon, so I hope that if we include it, people will start recognizing it. 

I don't think that it is hurting anything by being included but I will chat with them about the drop-down from the nav vs. the footer to inquire about keeping one over the other or both. I have a "list" of things that I want to go over with Olivia when she returns so I will add this item as well and follow back up.
