### ISSUE TITLE
footer: investigate using Markdown to resolve assets

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#54]
This comment (https://github.com/quarto-dev/quarto-cli/issues/9473#issuecomment-2075797413) suggests that we can shift to using Markdown rather than HTML for the shared footer icons and have those resources resolve during render.

We should try this, as it would mean less code-and-asset-copying for each project.

When making this change, add `alt` tags, as suggested here: https://github.com/posit-hosted/lucid-cloudyr-docs/pull/18/files#r1581427792

**Comment by AshleyHenry15** [comment]
I think that we tried this and it didn't work because we have to use "text" to implement our own icons in the footer?

**Comment by aronatkins** [comment]
I think the difference is that asset references in HTML text are not resolved, while asset references in Markdown text are. Still need to test, though.

**Comment by AshleyHenry15** [comment]
Link to initial slack thread from a while back: https://positpbc.slack.com/archives/C01LQETLA7L/p1710854855906749
