### ISSUE TITLE
dark mode: search colors need help

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#64]
The dark mode search overlay is styled in green and teal. The search results are provided in grey text on the green, which isn't terribly readable. The black-on-teal is more legible.

Searching with the example site:

<img width="1068" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/f3d32435-50ee-46d8-9472-ae1603961eae">

**Comment by AshleyHenry15** [comment]
Tagging @m-- for 👀
