### ISSUE TITLE
dark mode: code block without language identifier unreadable

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#66]
Code blocks without language identifiers are not readable in dark mode.

https://github.com/posit-dev/product-doc-theme/blob/fe0139961b72cb1400d42182ff88b189721ce796/index.qmd#L57-L65

Light theme:

<img width="822" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/32ed89ae-95ef-4c46-a30e-e753c84d3df5">

Dark theme:

<img width="815" alt="image" src="https://github.com/posit-dev/product-doc-theme/assets/362187/48a026b6-97fd-4b0f-8804-7d4b2adbd987">

**Comment by AshleyHenry15** [comment]
Tagging @m-- for 👀
