### ISSUE TITLE
dark mode: copy feedback is not legible

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/product-doc-theme#67]
When using the code-copy icon, the copying feedback is not legible.

Compare light and dark. The "Copied!" text is not visible with dark mode.

![code-select-dark](https://github.com/posit-dev/product-doc-theme/assets/362187/6c5db168-28f8-49c2-a0b9-c7549125c8ff)

![code-select-light](https://github.com/posit-dev/product-doc-theme/assets/362187/4ccf8d79-c481-435b-acbc-465bf7caab59)

**Comment by AshleyHenry15** [comment]
tagging @m-- for 👀
